name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Heroku using the API key
      - name: Log in to Heroku
        run: |
          echo "$HEROKU_API_KEY" | heroku auth:login --with-token
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      # Step 3: Deploy to Heroku
      - name: Deploy to Heroku
        run: |
          git remote add heroku https://git.heroku.com/java-movies-api.git
          git push heroku main