name: Deploy to Heroku

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Heroku

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Add Heroku remote and push to Heroku using API key for authentication
      - name: Deploy to Heroku
        run: |
          heroku git:remote -a java-movies-api
          git push heroku main