name: Deploy to Heroku

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Heroku

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main  # Ensure we are checking out the 'main' branch

      # Step 2: Fetch the latest changes from Heroku
      - name: Fetch Heroku main branch
        run: |
          git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/java-movies-api.git
          git fetch heroku main
          git merge FETCH_HEAD
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      # Step 3: Push to Heroku using API key for authentication
      - name: Deploy to Heroku
        run: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/java-movies-api.git main
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}